
sudo: false
language: cpp
#  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0
    packages:
    - g++-7
    - clang-5.0
    - lcov
matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - CXX = "g++-7"
        - CC = "gcc-7"
        - COVXX = "gcov-7"
    - os: linux
      compiler: clang
      env:
        - CC = "clang-5.0"
        - CXX = "clang++-5.0"
        - COVXX = "gcov-7"
before_install:
  - pip install --user cpp-coveralls
install:
  - ls
script:
#  - g++ -g src/main.cpp src/models/sudoku_field.cpp src/models/sudoku_tip_field.cpp src/models/tip_info.cpp src/sudoku_solver.cpp
  - make -f Makefile.mk test
  - buildTest/test.exe
#  - make test
after_success:
  - coveralls --root ./ -x gcov --gcov $COVXX -E ".*gtest.*" -E ".*CMakeFiles.*" --verbose
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
